apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dunena
  namespace: dunena
spec:
  ingressClassName: nginx
  rules:
    - host: dunena.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dunena
                port:
                  number: 80
